name: Staging deployment
on:
  push:
    branches:
      - dev

env:
  NODE_ENV: staging
  FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD: ${{secrets.FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD}}
  MATCH_PASSWORD: ${{secrets.MATCH_PASSWORD}}
  GIT_AUTH_TOKEN: ${{secrets.GIT_AUTH_TOKEN}}
  APPSTORE_KEY_ID: ${{secrets.APPSTORE_KEY_ID}}
  APPSTORE_ISSUER_ID: ${{secrets.APPSTORE_ISSUER_ID}}
  APPSTORE_KEY_CONTENT: ${{secrets.APPSTORE_KEY_CONTENT}}

jobs:
  deploy_to_testflight:
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6
          bundler-cache: true
      - name: Install Dependencies
        run: yarn install
      - name: Run Test
        run: yarn test
      - name: Build And Deploy
        run: cd ios && fastlane beta
